package com.github.jacknic.plugin.gradlehub.service

import com.github.jacknic.plugin.gradlehub.config.GradleHubSettings
import com.intellij.openapi.command.WriteCommandAction
import com.intellij.openapi.components.Service
import com.intellij.openapi.diagnostic.Logger
import com.intellij.openapi.project.Project
import com.intellij.openapi.vfs.LocalFileSystem
import com.intellij.openapi.vfs.VfsUtil
import com.intellij.openapi.vfs.VirtualFile
import java.io.File

/**
 * Project-level service that manages the global `init.gradle` proxy script.
 *
 * Generates a Gradle init script at `~/.gradle/init.d/gradlehub-mirror.gradle`
 * that replaces repository URLs with mirror addresses for all Gradle builds.
 * This approach requires no modification to project files.
 *
 * All pure generation logic is exposed as companion object methods for testability.
 */
@Service(Service.Level.PROJECT)
class InitGradleService(val project: Project) {

    companion object {
        private val LOG = Logger.getInstance(InitGradleService::class.java)

        const val INIT_SCRIPT_NAME = "gradlehub-mirror.gradle"
        const val INIT_D_DIR_NAME = "init.d"
        const val BACKUP_SUFFIX = ".gradlehub.bak"
        const val MARKER_LINE = "// GradleHub-InitGradle-AutoGenerated"

        /**
         * Generate the content of the `init.gradle` proxy script.
         *
         * The generated script uses Gradle's `allprojects` and `buildscript` hooks
         * to prepend the mirror repository before any other repositories.
         *
         * @param mirrorUrl the repository mirror URL (e.g. `https://maven.aliyun.com/repository/public`)
         * @return the complete init script content
         */
        fun generateInitGradleContent(mirrorUrl: String): String {
            return """
                |$MARKER_LINE
                |// This file is auto-generated by the GradleHub IntelliJ plugin.
                |// Do not modify this file manually. Use the plugin to manage it.
                |
                |allprojects {
                |    buildscript {
                |        repositories {
                |            maven { url '$mirrorUrl' }
                |        }
                |    }
                |    repositories {
                |        maven { url '$mirrorUrl' }
                |    }
                |}
                |
                |settingsEvaluated {
                |    pluginManagement {
                |        repositories {
                |            maven { url '$mirrorUrl' }
                |        }
                |    }
                |}
            """.trimMargin()
        }

        /**
         * Check if the given content was generated by GradleHub.
         *
         * @param content the file content to check
         * @return true if the content contains the GradleHub marker line
         */
        fun isGradleHubManaged(content: String): Boolean = content.contains(MARKER_LINE)

        /**
         * Get the path to the `init.d` directory.
         *
         * @param gradleHome the effective Gradle home directory (e.g. `~/.gradle`)
         * @return the [File] pointing to the `init.d` directory
         */
        fun getInitDir(gradleHome: String): File {
            return File(gradleHome, INIT_D_DIR_NAME)
        }

        /**
         * Get the path to the GradleHub init script file.
         *
         * @param gradleHome the effective Gradle home directory
         * @return the [File] pointing to the init script
         */
        fun getInitScriptFile(gradleHome: String): File {
            return File(getInitDir(gradleHome), INIT_SCRIPT_NAME)
        }

        /**
         * Get the path to the backup of the init script file.
         *
         * @param gradleHome the effective Gradle home directory
         * @return the [File] pointing to the backup
         */
        fun getInitScriptBackupFile(gradleHome: String): File {
            return File(getInitDir(gradleHome), INIT_SCRIPT_NAME + BACKUP_SUFFIX)
        }
    }

    /**
     * Check if the init.gradle proxy is currently applied.
     *
     * @return true if the GradleHub init script file exists
     */
    fun isProxyApplied(): Boolean {
        val settings = GradleHubSettings.getInstance()
        val gradleHome = settings.getEffectiveGradleHome()
        val initScript = getInitScriptFile(gradleHome)
        return initScript.exists()
    }

    /**
     * Apply the init.gradle proxy by generating the init script file.
     *
     * Steps:
     * 1. Validate settings
     * 2. Ensure the `init.d` directory exists
     * 3. Back up any existing non-GradleHub init script with the same name
     * 4. Write the generated init script
     *
     * @return true if the proxy was successfully applied, false otherwise
     */
    fun applyProxy(): Boolean {
        val settings = GradleHubSettings.getInstance()
        if (!settings.mirrorEnabled || !settings.initGradleEnabled) {
            LOG.warn("Init.gradle proxy is disabled in settings")
            return false
        }
        if (settings.repositoryMirrorUrl.isBlank()) {
            LOG.warn("Repository mirror URL is not configured")
            return false
        }

        val gradleHome = settings.getEffectiveGradleHome()
        val initDir = getInitDir(gradleHome)
        val initScript = getInitScriptFile(gradleHome)
        val backupFile = getInitScriptBackupFile(gradleHome)

        try {
            // Ensure init.d directory exists
            if (!initDir.exists()) {
                val created = initDir.mkdirs()
                if (!created) {
                    LOG.error("Failed to create init.d directory: ${initDir.absolutePath}")
                    return false
                }
            }

            // If init script already exists and is managed by us, skip
            if (initScript.exists()) {
                val existingContent = initScript.readText(Charsets.UTF_8)
                if (isGradleHubManaged(existingContent)) {
                    // Update the existing script with current settings
                    LOG.info("Updating existing GradleHub init script")
                } else {
                    // Back up the existing user file before overwriting
                    backupFile.writeText(existingContent, Charsets.UTF_8)
                    LOG.info("Backed up existing init script to ${backupFile.name}")
                }
            }

            // Generate and write the init script
            val content = generateInitGradleContent(settings.repositoryMirrorUrl)
            initScript.writeText(content, Charsets.UTF_8)
            LOG.info("Generated init script: ${initScript.absolutePath}")
            return true
        } catch (e: Exception) {
            LOG.error("Failed to apply init.gradle proxy", e)
            return false
        }
    }

    /**
     * Restore the original state by removing the GradleHub init script.
     *
     * If a backup of a pre-existing init script exists, it is restored.
     *
     * @return true if the original state was successfully restored, false otherwise
     */
    fun restoreOriginal(): Boolean {
        val settings = GradleHubSettings.getInstance()
        val gradleHome = settings.getEffectiveGradleHome()
        val initScript = getInitScriptFile(gradleHome)
        val backupFile = getInitScriptBackupFile(gradleHome)

        try {
            if (!initScript.exists()) {
                LOG.info("Init script does not exist; nothing to restore")
                return false
            }

            if (backupFile.exists()) {
                // Restore the user's original init script
                val originalContent = backupFile.readText(Charsets.UTF_8)
                initScript.writeText(originalContent, Charsets.UTF_8)
                backupFile.delete()
                LOG.info("Restored original init script from backup")
            } else {
                // Simply delete the GradleHub-managed script
                val deleted = initScript.delete()
                if (!deleted) {
                    LOG.warn("Failed to delete init script: ${initScript.absolutePath}")
                    return false
                }
                LOG.info("Deleted GradleHub init script")
            }
            return true
        } catch (e: Exception) {
            LOG.error("Failed to restore init.gradle", e)
            return false
        }
    }
}
