package com.github.jacknic.plugin.gradlehub.service

import com.intellij.testFramework.fixtures.BasePlatformTestCase
import java.io.File
import java.nio.file.Files

/**
 * Unit tests for [InitGradleService] companion object methods.
 *
 * Tests the pure generation logic and file path computation
 * that does not depend on IntelliJ project context.
 */
class InitGradleServiceTest : BasePlatformTestCase() {

    // ---- generateInitGradleContent ----

    fun testGenerateInitGradleContent_containsMarker() {
        val content = InitGradleService.generateInitGradleContent("https://maven.aliyun.com/repository/public")
        assertTrue(content.contains(InitGradleService.MARKER_LINE))
    }

    fun testGenerateInitGradleContent_containsAllprojects() {
        val content = InitGradleService.generateInitGradleContent("https://maven.aliyun.com/repository/public")
        assertTrue(content.contains("allprojects"))
    }

    fun testGenerateInitGradleContent_containsBuildscript() {
        val content = InitGradleService.generateInitGradleContent("https://maven.aliyun.com/repository/public")
        assertTrue(content.contains("buildscript"))
    }

    fun testGenerateInitGradleContent_containsMirrorUrl() {
        val mirrorUrl = "https://maven.aliyun.com/repository/public"
        val content = InitGradleService.generateInitGradleContent(mirrorUrl)
        // Should contain the URL in multiple places (buildscript repos + project repos + pluginManagement)
        val occurrences = content.split(mirrorUrl).size - 1
        assertTrue("Expected at least 3 occurrences of mirror URL, got $occurrences", occurrences >= 3)
    }

    fun testGenerateInitGradleContent_containsPluginManagement() {
        val content = InitGradleService.generateInitGradleContent("https://mirror.example.com/")
        assertTrue(content.contains("settingsEvaluated"))
        assertTrue(content.contains("pluginManagement"))
    }

    fun testGenerateInitGradleContent_containsMavenDeclaration() {
        val content = InitGradleService.generateInitGradleContent("https://maven.aliyun.com/repository/public")
        assertTrue(content.contains("maven { url 'https://maven.aliyun.com/repository/public' }"))
    }

    fun testGenerateInitGradleContent_containsAutoGeneratedComment() {
        val content = InitGradleService.generateInitGradleContent("https://mirror.example.com/")
        assertTrue(content.contains("auto-generated"))
        assertTrue(content.contains("GradleHub"))
    }

    fun testGenerateInitGradleContent_differentUrls() {
        val url1 = "https://maven.aliyun.com/repository/public"
        val url2 = "https://repo.huaweicloud.com/repository/maven/"

        val content1 = InitGradleService.generateInitGradleContent(url1)
        val content2 = InitGradleService.generateInitGradleContent(url2)

        assertTrue(content1.contains(url1))
        assertFalse(content1.contains(url2))
        assertTrue(content2.contains(url2))
        assertFalse(content2.contains(url1))
    }

    // ---- isGradleHubManaged ----

    fun testIsGradleHubManaged_withMarker() {
        val content = InitGradleService.generateInitGradleContent("https://mirror.example.com/")
        assertTrue(InitGradleService.isGradleHubManaged(content))
    }

    fun testIsGradleHubManaged_withoutMarker() {
        val content = """allprojects {
            |    repositories {
            |        mavenCentral()
            |    }
            |}
        """.trimMargin()
        assertFalse(InitGradleService.isGradleHubManaged(content))
    }

    fun testIsGradleHubManaged_emptyContent() {
        assertFalse(InitGradleService.isGradleHubManaged(""))
    }

    // ---- getInitDir ----

    fun testGetInitDir() {
        val gradleHome = "/home/user/.gradle"
        val initDir = InitGradleService.getInitDir(gradleHome)
        assertEquals("/home/user/.gradle/init.d", initDir.absolutePath)
    }

    fun testGetInitDir_windowsPath() {
        val gradleHome = "C:\\Users\\user\\.gradle"
        val initDir = InitGradleService.getInitDir(gradleHome)
        assertTrue(initDir.absolutePath.endsWith("init.d"))
    }

    // ---- getInitScriptFile ----

    fun testGetInitScriptFile() {
        val gradleHome = "/home/user/.gradle"
        val scriptFile = InitGradleService.getInitScriptFile(gradleHome)
        assertEquals("gradlehub-mirror.gradle", scriptFile.name)
        assertTrue(scriptFile.absolutePath.contains("init.d"))
    }

    // ---- getInitScriptBackupFile ----

    fun testGetInitScriptBackupFile() {
        val gradleHome = "/home/user/.gradle"
        val backupFile = InitGradleService.getInitScriptBackupFile(gradleHome)
        assertEquals("gradlehub-mirror.gradle.gradlehub.bak", backupFile.name)
    }

    // ---- File I/O integration tests ----

    fun testFileGenerationAndDetection() {
        val tempDir = Files.createTempDirectory("gradlehub-test").toFile()
        try {
            val initDir = File(tempDir, "init.d")
            initDir.mkdirs()

            val scriptFile = File(initDir, InitGradleService.INIT_SCRIPT_NAME)
            val mirrorUrl = "https://maven.aliyun.com/repository/public"

            // Generate and write
            val content = InitGradleService.generateInitGradleContent(mirrorUrl)
            scriptFile.writeText(content, Charsets.UTF_8)

            // Verify file exists and is detected
            assertTrue(scriptFile.exists())
            val readContent = scriptFile.readText(Charsets.UTF_8)
            assertTrue(InitGradleService.isGradleHubManaged(readContent))
            assertTrue(readContent.contains(mirrorUrl))

            // Simulate restore (delete the file)
            scriptFile.delete()
            assertFalse(scriptFile.exists())
        } finally {
            tempDir.deleteRecursively()
        }
    }

    fun testFileGenerationWithBackupRestore() {
        val tempDir = Files.createTempDirectory("gradlehub-test").toFile()
        try {
            val initDir = File(tempDir, "init.d")
            initDir.mkdirs()

            val scriptFile = File(initDir, InitGradleService.INIT_SCRIPT_NAME)
            val backupFile = File(initDir, InitGradleService.INIT_SCRIPT_NAME + InitGradleService.BACKUP_SUFFIX)

            // Simulate a pre-existing user init script
            val userContent = """allprojects {
                |    repositories {
                |        mavenLocal()
                |    }
                |}
            """.trimMargin()
            scriptFile.writeText(userContent, Charsets.UTF_8)

            // Back it up before overwriting
            backupFile.writeText(userContent, Charsets.UTF_8)

            // Overwrite with GradleHub content
            val mirrorUrl = "https://repo.huaweicloud.com/repository/maven/"
            val gradleHubContent = InitGradleService.generateInitGradleContent(mirrorUrl)
            scriptFile.writeText(gradleHubContent, Charsets.UTF_8)

            // Verify GradleHub content
            assertTrue(InitGradleService.isGradleHubManaged(scriptFile.readText(Charsets.UTF_8)))

            // Restore from backup
            val restoredContent = backupFile.readText(Charsets.UTF_8)
            scriptFile.writeText(restoredContent, Charsets.UTF_8)
            backupFile.delete()

            // Verify restored
            assertEquals(userContent, scriptFile.readText(Charsets.UTF_8))
            assertFalse(backupFile.exists())
        } finally {
            tempDir.deleteRecursively()
        }
    }
}
